<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<div class="mag-task50">
    <p>It's MAG-50 images block</p>
    <div class="mag-task50-imgWrap" id="task50-wrap" style="display: flex;" data-mage-init='{"Magento_Cms/js/mag50":{}}'>
        <img src="<?= $block->escapeUrl($block->getViewFileUrl('images/task32-1.jpeg')) ?>"
             alt="<?= $block->escapeHtmlAttr(__('Loading...')) ?>"
             class="mag-task50-img"
             style="width: 200px; margin: 0 10px;">
        <img src="<?= $block->escapeUrl($block->getViewFileUrl('images/task32-2.jpeg')) ?>"
             alt="<?= $block->escapeHtmlAttr(__('Loading...')) ?>"
             class="mag-task50-img"
             style="width: 200px; margin: 0 10px;">
        <img src="<?= $block->escapeUrl($block->getViewFileUrl('images/task32-3.jpeg')) ?>"
             alt="<?= $block->escapeHtmlAttr(__('Loading...')) ?>"
             class="mag-task50-img"
             style="width: 400px; margin: 0 10px;">
    </div>
</div>
