<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

?>
<ul>
    <li><a href="http://magento-study.loc/women.html">women</a></li>
    <li><a href="http://magento-study.loc/men.html">men</a></li>
    <li><a href="http://magento-study.loc/gear.html">gear</a></li>
    <li><a href="http://magento-study.loc/training.html">training</a></li>
    <li><a href="http://magento-study.loc/sale.html">sale</a></li>
</ul>
